# Generated by Django 3.0.3 on 2021-07-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="illness",
            field=models.ManyToManyField(null=True, to="diagnose.Illness"),
        ),
    ]
