# Generated by Django 3.0.3 on 2021-07-06 04:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, unique=True)),
                ('Severity', models.CharField(max_length=30)),
                ('Symptom', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'gradual or sudden change in the quality of your vision followed by appearance of straight lines as distorted'), ('item_key2', 'Blurriness of central vision'), ('item_key3', 'Partial vision loss marked by formation of blind spots (scotomas)'), ('item_key4', 'Problem seeing in dim light'), ('item_key5', 'Objects appearing smaller than their actual size, as viewed with one eye and then the other'), ('item_key6', 'lacking typical symptoms like pain, tearing or redness of eyes'), ('item_key7', 'Blurred, clouded or dim vision'), ('item_key8', 'Problem seeing at night'), ('item_key9', 'Problem seeing through light and glare'), ('item_key10', 'Seeing ‘halos’ around lights'), ('item_key11', 'Frequently changing contact lens prescription or eyeglasses'), ('item_key12', 'Faded view of colors'), ('item_key13', 'Tunnel vision'), ('item_key14', 'Peripheral vision loss, gradually affecting both eyes in most cases'), ('item_key15', 'Severe pain in eyes accompanied by nausea and vomiting in most cases'), ('item_key16', 'Sudden visual disturbance in low light conditions'), ('item_key17', 'Halos around lights'), ('item_key19', 'Redness of the eyes')], max_length=188, null=True)),
            ],
        ),
    ]
