# Generated by Django 3.0.3 on 2021-07-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consults',
            name='illness',
        ),
    ]
