# Generated by Django 3.0.3 on 2021-07-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='Treatement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
