# Generated by Django 3.0.3 on 2021-07-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0002_illness_treatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='Severity',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('SIGNIFICANT', 'Significant'), ('CRITICAL', 'Critical')], default='PATIENT', max_length=50, verbose_name='Severity'),
        ),
    ]
