# Generated by Django 3.0.3 on 2021-07-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0003_auto_20210706_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='Severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MINOR', 'Minor'), ('SIGNIFICANT', 'Significant'), ('CRITICAL', 'Critical')], default='MINOR', max_length=50, verbose_name='Severity'),
        ),
    ]
