# Generated by Django 3.0.3 on 2021-07-06 22:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0005_consults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='illness',
            name='Symptom',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gradual or sudden change in the quality of your vision followed by appearance of straight lines as distorted', 'gradual or sudden change in the quality of your vision followed by appearance of straight lines as distorted'), ('Blurriness of central vision', 'Blurriness of central vision'), ('Partial vision loss marked by formation of blind spots (scotomas)', 'Partial vision loss marked by formation of blind spots (scotomas)'), ('Problem seeing in dim light', 'Problem seeing in dim light'), ('Objects appearing smaller than their actual size, as viewed with one eye and then the other', 'Objects appearing smaller than their actual size, as viewed with one eye and then the other'), ('lacking typical symptoms like pain, tearing or redness of eyes', 'lacking typical symptoms like pain, tearing or redness of eyes'), ('Blurred, clouded or dim vision', 'Blurred, clouded or dim vision'), ('Problem seeing at night', 'Problem seeing at night'), ('Problem seeing through light and glare', 'Problem seeing through light and glare'), ('Seeing ‘halos’ around lights', 'Seeing ‘halos’ around lights'), ('Frequently changing contact lens prescription or eyeglasses', 'Frequently changing contact lens prescription or eyeglasses'), ('Faded view of colors', 'Faded view of colors'), ('Tunnel vision', 'Tunnel vision'), ('Peripheral vision loss, gradually affecting both eyes in most cases', 'Peripheral vision loss, gradually affecting both eyes in most cases'), ('Severe pain in eyes accompanied by nausea and vomiting in most cases', 'Severe pain in eyes accompanied by nausea and vomiting in most cases'), ('Sudden visual disturbance in low light conditions', 'Sudden visual disturbance in low light conditions'), ('Halos around lights', 'Halos around lights'), ('Redness of the eyes', 'Redness of the eyes')], max_length=831, null=True),
        ),
    ]
