# Generated by Django 3.0.3 on 2021-07-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0008_auto_20210707_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='symptoms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
