# Generated by Django 3.0.3 on 2021-07-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0009_auto_20210707_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
