# Generated by Django 3.0.3 on 2021-07-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0010_auto_20210707_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='Symptom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
